### ISSUE TITLE
Feature request: `long_desc_file` argument

### ISSUE THREAD

**Issue by carlo** [dazuma/toys#15]
I'd like to have a new `long_desc_file` argument which would set the long description to the contents of a file; this way, I could split the actual task and its description into an `.rb` file.

I tend to write rather thorough long descriptions, and that results in me having to scroll down one or two pages to see the actual code when editing the task.  Right now, I'm using the following code to achieve that goal:

```ruby
long_desc File.readlines(File.dirname(__FILE__) + '/_docs/my-task.txt')
```

It works, but it's hardly ideal. I think something like this would be cleaner/nicer:

1. `long_desc_file` (no arguments) loads the long desc from a file w/ the same name as the current task, but a different extension (e.g. `example/my-task.rb` → `example/my-task.txt` or `example/my-task.md` etc.)
2. `long_desc_file './some-documentation.txt'` loads the long desc from a named file relative to the current tool's source.

Thanks for your consideration! :)

**Comment by carlo** [comment]
FWIW, this monkey patch currently works well for me.

```ruby
module Toys
  module DSL
    module Tool
      def long_desc_file(filename = nil)
        filename ||= (File.basename(source_info.to_s, '.rb') + '.txt')
        path = File.join(File.dirname(source_info.to_s), filename)
        strs = File.readlines(path).map { |s| [s] }

        DSL::Tool.current_tool(self, true)&.append_long_desc(strs)
        self
      end
    end
  end
end
```

I should mention that all lines in my description files are at most 80 chars long and that I have no need for the automatic word-wrap behaviour. That's the reason for wrapping each line in an array before passing them on to `.append_long_desc`, to prevent that.

**Comment by dazuma** [comment]
I think this is a good idea. I hadn't thought about what it would look like to have non-ruby files directly in the toys directory. But for the purpose of defining long descriptions in parallel files, it does seem to make sense.

I'm a little wary of the "default" behavior (i.e. no arguments) because toys files will commonly define multiple tools, and it seems that would cause confusion. It also seems that would restrict us from supporting multiple formats in the future. (As you suggested, for example, `.txt`, `.md`, and maybe others.) Because then it's ambiguous which file should be chosen.

What would you say if I just make the file name required?

Also, I'm thinking of making `file:` a keyword argument of `long_desc` instead of defining a separate directive. For example:

```ruby
long_desc file: "my-tool.txt"
```

This would give us the flexibility of adding additional keyword arguments in the future (for example, `data:` to look it up from the data directory, or possibly even `url:` or `git:`) without requiring us to create more and more directives.

**Comment by carlo** [comment]
Valid points, all. I hadn't thought about the case of multiple tools living in the same toys file because that's not how I (personally) use it. Making the file name required makes absolute sense, and making it a keyword argument should give you a lot of freedom for future enhancements.

Thanks! :)

**Comment by dazuma** [comment]
Closing this as fixed, since the code is in master. I expect to release this in version 0.10.0 shortly.
