### ISSUE TITLE
Prevent requesting toys in parent directories

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#57]
Hello.

I have a bad case: a gem (which has `.toys.rb`), which generates a project (with `.toys/.toys.rb`). I'm trying to test it, generating `foo_bar/` project inside a gem directory, `cd foo_bar/` then and `toys tool-of-project`. The  `.toys` of project has `include :bundler, static: true`, and… it exits with the error from gem's toys (in a parent directory of a project):

```
LoadError: cannot load such file -- gem_toys
     28: /home/alex/.rbenv/versions/2.6.6/bin/toys:23:in `<main>'
     27: /home/alex/.rbenv/versions/2.6.6/bin/toys:23:in `load'
     26: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-0.10.5/bin/toys:11:in `<top (required)>'
     25: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:423:in `run'
     24: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/errors.rb:90:in `capture'
     23: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:424:in `block in run'
     22: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:139:in `lookup'
     21: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:139:in `loop'
     20: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:140:in `block in lookup'
     19: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:160:in `lookup_specific'
     18: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:276:in `load_for_prefix'
     17: /home/alex/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
     16: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:280:in `block in load_for_prefix'
     15: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:280:in `each'
     14: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:285:in `block (2 levels) in load_for_prefix'
     13: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:388:in `load_validated_path'
     12: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/loader.rb:397:in `load_relevant_path'
     11: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/input_file.rb:26:in `evaluate'
     10: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/dsl/tool.rb:1694:in `prepare'
      9: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/input_file.rb:27:in `block in evaluate'
      8: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/errors.rb:70:in `capture_path'
      7: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/input_file.rb:29:in `block (2 levels) in evaluate'
      6: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/input_file.rb:29:in `eval'
      5: /home/alex/Projects/ruby/flame-cli/.toys.rb:in `__binding'
      4: /home/alex/Projects/ruby/flame-cli/.toys.rb:1:in `<module:M47291429051140__toys_rb>'
      3: /home/alex/Projects/ruby/flame-cli/.toys.rb:1:in `class_eval'
      2: /home/alex/Projects/ruby/flame-cli/.toys.rb:9:in `block in <module:M47291429051140__toys_rb>'
      1: /home/alex/Projects/ruby/flame-cli/.toys.rb:9:in `require'
Error while loading Toys config!
    LoadError: cannot load such file -- gem_toys
    in config file: /home/alex/Projects/ruby/flame-cli/.toys.rb:9
```

I've found a documentation:

> ### The Toys search path
> So far we have seen how to define tools by writing a .toys.rb file in the current directory, or by writing files inside a .toys directory in the current directory. These tools are "scoped" to the current directory. If you move to a different directory, they may not be available.
> 
> When Toys runs, it looks for tools in a search path. Specifically:
> 
> 1. It looks for a .toys.rb file and/or a .toys directory in the current working directory.
> 2. It does the same in the parent directory of the current directory, and then its parent, and so on until it hits either the root of the file system or one of the global directories described in (3).
> 3. It looks in a list of global directories, specified in the environment variable TOYS_PATH. This variable can contain a colon-delimited list of directory paths. If the variable is not set, the current user's home directory, and the system configuration directory (/etc on unix systems) are used by default. Toys does not search parents of global directories.
> It uses the first implementation that it finds for the requested tool. For example, if the tool greet is defined in the .toys.rb file in the current working directory, and also in the .toys/greet.rb file of the parent directory, it will use the version in the current directory.
> 
> This means you could write a default implementation for a tool in your home directory, and override it in the current directory. For example, you could define a tool get-credentials in your home directory that gets credentials you need for most of your projects. But maybe on particular project requires different credentials, so you could define a different get-credentials tool in that project's directory.

As I understand, you wanted to have global `toys`: and for specific projects, and with common tools (from a home directory, for example). But it conflicts with `include :bundler, static: true` and dependencies of toys from parent directories.

**Comment by dazuma** [comment]
I think we could provide a directive that prevents the search path from proceeding any further than the current directory. For example, we could add support for this in `.toys.rb`:

```ruby
# Make the current toys directory the final directory in the search path.
# That is, don't search any more parent directories from this point.
terminate_search!

tool "my-tool" do #...
```

There would be some limitations, though. It would not be effective if files from further up the search path have already been loaded. Because of how the loader works, that means it would need to appear in a top level `.toys.rb` file. It would not work if it appeared in a named tool file or inside a tool block, because by the time those are executed, toplevel files from further up the directory tree may already have been loaded.

So I'll look into adding this feature.

I do want to clarify, though, that this really isn't a conflict with the search path. You don't need to have parent directories or a search path at all, to encounter this issue. _Any_ time you `include :bundler, static: true`, you are potentially conflicting with someone else's bundle. For example, you could have two different tools, even in the same `.toys.rb` file, and if one of them loads a bundle statically (at tool definition time), and the other tries to load a different bundle, you'll get this same error.

So really, this is just a limitation of bundler, and a risk of using `static: true`. Because of the way bundler works, as soon as one tool definition installs a bundle, you're stuck with it. That's why `include :bundler` by default does _not_ set `static: true`, which means it doesn't install the bundle until it decides to _run that specific tool_. Now I understand that sometimes `static: true` is needed because a gem is required in order to define a tool, but the cost is that you risk this issue.

**Comment by AlexWayfer** [comment]
> ```ruby
> terminate_search!
> ```

`prevent_` may be more accurate, I think.



> There would be some limitations, though. It would not be effective if files from further up the search path have already been loaded. Because of how the loader works, that means it would need to appear in a top level `.toys.rb` file. It would not work if it appeared in a named tool file or inside a tool block, because by the time those are executed, toplevel files from further up the directory tree may already have been loaded.

It's OK for me.



> For example, you could have two different tools, even in the same `.toys.rb` file, and if one of them loads a bundle statically (at tool definition time), and the other tries to load a different bundle, you'll get this same error.

How another tool in the same `.toys.rb` file can "load a different bundle"?



> So really, this is just a limitation of bundler, and a risk of using `static: true`.

Sorry, I can't find any documentation about `:static` option in https://dazuma.github.io/toys/gems/toys/v0.10.5/file.guide.html, so maybe I don't understand it correctly.

**Comment by AlexWayfer** [comment]
I've tried to remove `static: true` from (application, not gem) project-root `.toys.rb` and it fails when I call commands like `sh 'rbenv local 2.7.1.'`, `sh 'gem install bundler'` or `sh 'bundle install'`:

```
> rbenv install -s 2.7.1
> rbenv local 2.7.1
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
	11: from /home/alex/.rbenv/versions/2.7.1/bin/bundler:23:in `<main>'
	10: from /home/alex/.rbenv/versions/2.7.1/bin/bundler:23:in `load'
	 9: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundler:4:in `<top (required)>'
	 8: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundler:4:in `load'
	 7: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `<top (required)>'
	 6: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `require_relative'
	 5: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	 4: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	 3: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	 2: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	 1: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
> gem install bundler --conservative
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
	9: from /home/alex/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
	8: from /home/alex/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
	7: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `<top (required)>'
	6: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `require_relative'
	5: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	4: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	3: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	2: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	1: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
> bundle install
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/alex/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
	9: from /home/alex/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
	8: from /home/alex/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
	7: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `<top (required)>'
	6: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `require_relative'
	5: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	4: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	3: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	2: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	1: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
```

With `static: true` everything is OK.

**Comment by dazuma** [comment]
>> For example, you could have two different tools, even in the same .toys.rb file, and if one of them loads a bundle statically (at tool definition time), and the other tries to load a different bundle, you'll get this same error.
>
> How another tool in the same .toys.rb file can "load a different bundle"?

In most simple cases, you'll have a single `Gemfile` that applies to your entire project, located in the project root directory (in the same place as your `.toys` directory, i.e. in what Toys calls the "context directory"). I'm guessing that's how your project is set up now. This works because, in most simple cases, you have a single set of gems that works for every tool you define for your project.

However, in a more complex project, it is possible that different tools might require different sets of gems. One common case that I run into is when I want to test against different versions of a dependency. (Some people us [Appraisal](https://github.com/thoughtbot/appraisal) for this purpose, but since both Appraisal and Toys are trying to hack Bundler, it's risky to try to combine them, and I don't recommend it.) So Toys also allows you to specify a Gemfile specific to a tool, by including the Gemfile in the Toys directory, next to the Toys file that defines the tool.

By default, `include :bundler` will first look for a Gemfile next to the Toys file that defines the tool. Failing that, it will look in the context directory (i.e. next to the `.toys` directory). Failing that, it will look in the current working directory. You can also customize that search path, and even provide a specific directory to look for a Gemfile. (See the [documentation](https://dazuma.github.io/toys/gems/toys-core/v0.10.5/Toys/StandardMixins/Bundler) on the bundler mixin for more info.)

So the upshot is, you _can_ set up different tools to have "different bundles". But that leads to a problem. If you have defined multiple tools, and each one uses a different Gemfile, then how is that possible? Bundler lets you set up only one Gemfile at a time. Once you've done a "bundle setup" with one Gemfile, you're locked to those gems and versions. You cannot set up a different Gemfile.

Toys deals with this problem by _delaying_ bundle setup until it knows exactly which tool will be run, and then setting up _only_ that tool's bundle. That is, when you say `include :bundler`, Toys does _not_ setup the bundle immediately. Instead, it waits until it determines that the tool is actually going to get run, and sets up the bundle when initializing that tool for running. So if you:

```ruby
# .toys.rb

tool "foo" do
  # loads /path/to/foo_bundle/Gemfile
  include :bundler, search_dirs: "/path/to/foo_bundle"
  def run
    puts "running foo"
  end
end

tool "bar" do
  # loads /path/to/bar_bundle/Gemfile
  include :bundler, search_dirs: "/path/to/bar_bundle"
  def run
    puts "running bar"
  end
end
```

Now `toys foo` will use /path/to/foo_bundle/Gemfile and never touch bar_bundle. And if you just run `toys`, it never loads either bundle.

That leads us to your next question: what does `static: true` actually mean?

Sometimes you need the gem dependencies in order to _define_ a tool (not just in order to _run_ the tool). For example, if a gem dependency defines a mixin that you want to use. When you use `static: true`, that tells Toys to set up the bundle _immediately_ rather than waiting until Toys knows it needs to run the tool. Then you can use the gem dependencies in the bundle, as part of the tool's definition.

```ruby
# .toys.rb

tool "foo" do
  # The Gemfile includes a gem that defines MyMixin.
  include :bundler, static: true
  # Since we used static: true, the gems are available right now
  # while the tool is being defined. So we can do this:
  require "my_mixin"
  include MyMixin
  #...
```

However, the trade-off here is that the problem of multiple Gemfiles comes back if you use `static: true`. As soon as the above tool is _defined_, you're stuck with its Gemfile. It's set up already. So no other tools can use a different Gemfile. That's why `static: true` is not the default. It's more intrusive, so you should use it only if you need the gem dependencies to _define_ the tool (rather than just to run it).

Now the good news is, Toys _also_ tries to delay _defining_ a tool until it thinks it might need it. So if you "scope" your `include :bundler, static: true` inside whichever `tool` block it is relevant to, that can help because it won't actually get executed unless the tool, or one of its subtools, will be executed. But if you `include :bundler, static: true` at the "top level" of a toys file (not inside a tool definition) then it always gets executed, and you're stuck with that Gemfile. As a result, it's good practice to keep `include :bundler` declarations scoped inside whichever tool needs it.

I know that's a lot of info. But hopefully it will make some sense of why things are set up the way they are.

**Comment by AlexWayfer** [comment]
Thank you! I like flexibility, so maybe it's not the necessary, but a way to resolve problems.
