### ISSUE TITLE
Split project into two for two gems

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#6]
Hello.

Please, split the project. Currently, you can take out the `toys-core`.

If I have a patch, and want to use it from my fork, generally I can add:

```diff
# Gemfile
  gem 'toys'
+ gem 'toys-core', github: 'AlexWayfer/toys-core', branch: 'my-patch'
```

But for current setup I don't know how to switch (noway, as I guess).

This is a bad practice at all.

**Comment by AlexWayfer** [comment]
UPD: I found `glob` option, so this works:

```diff
# Gemfile
- gem 'toys'
+ gem 'toys', github: 'AlexWayfer/toys`, glob: 'toys/*.gemspec', branch: 'my-patch'
+ gem 'toys-core', github: 'AlexWayfer/toys`, glob: 'toys-core/*.gemspec', branch: 'my-patch'
```

But it's ugly.

**Comment by dazuma** [comment]
Please use the `glob` argument. i know it's an extra argument, and I know it's often considered good practice to have one repo per gem. However, in this case the two gems are coupled closely enough that splitting the repo in two would cause too many workflow issues. For example, it's common for a change to affect both gems, and running tests for such a change becomes a problem if they're in separate repos. (This is similar to Rails, which also keeps its gems in subdirectories of the same repo, for the same reason.)

**Comment by AlexWayfer** [comment]
OK, maybe… but why do you need to separate this project into two gems at all?

**Comment by dazuma** [comment]
There are two different use cases. The `toys` command line tool itself, and the underlying command line framework that you can use to build command line tools. I needed to make it possible for a standalone tool to depend on `toys-core`, but not install the `toys` binary.

**Comment by AlexWayfer** [comment]
> For example, it's common for a change to affect both gems, and running tests for such a change becomes a problem if they're in separate repos.

Maybe there is can be `Gemfile` with `:test` group and `gem 'toys-core', path: '../toys-core'`. Like… adjacent directory, previously git-cloned manually or by command from repo.

**Comment by dazuma** [comment]
Yes, it is possible to hack something together, but it quickly becomes inconvenient (and, as you said, ugly). For example, this works for local tests, but if someone else wants to test my branch, now they have to set things up exactly the same way: they'd have to clone both repositories and make sure they're in the right path in their local filesystem. And then you have to consider CI. Modern CI systems are generally designed to treat repositories in isolation. It's _possible_ to work around it, but ugly and very nonstandard. And so far we've talked only about tests. The release process is affected as well because, like Rails, Toys always releases both gems together. When I weigh all that against just the inconvenience of adding a `glob` argument for the case when you want to depend on the version in Github, I tend to lean toward keeping a single repo.

That said, you're right to bring this up. It would probably be worth documenting how to use the `glob` argument to depend on code from Github, because it's a bit atypical.

**Comment by dazuma** [comment]
By the way, I'd love to merge your PR, #5. It handles a case that I totally forgot about. There's just one small fix I was hoping you could make.

**Comment by AlexWayfer** [comment]
Okay, let's try with `glob`, thank you.

I'm talking not only about #5, maybe I'll create more PRs, but at least now I know how to switch correctly.
