### ISSUE TITLE
`system` with `include :bundler`

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#65]
Hello.

I have `include :bundler, static: true` in my `.toys.rb` file.

And in one of tools I'm trying to call:

```ruby
system 'bundle exec pumactl ...'
```

This command loads files with:

```ruby
require 'bundler/setup'
Bundler.require(:specific_groups)
```

And I'm getting:

```
> bundle exec pumactl start
bundler: failed to load command: pumactl (/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/pumactl)
LoadError: cannot load such file -- flame/r18n
  /home/alex/Projects/ruby/test/foo_bar/config/processors/r18n.rb:3:in `require'
  /home/alex/Projects/ruby/test/foo_bar/config/processors/r18n.rb:3:in `<top (required)>'
  /home/alex/Projects/ruby/test/foo_bar/config/main.rb:65:in `require_relative'
  /home/alex/Projects/ruby/test/foo_bar/config/main.rb:65:in `block (2 levels) in <top (required)>'
  /home/alex/Projects/ruby/test/foo_bar/config/main.rb:64:in `each'
  /home/alex/Projects/ruby/test/foo_bar/config/main.rb:64:in `block in <top (required)>'
  /home/alex/Projects/ruby/test/foo_bar/config/main.rb:52:in `instance_exec'
  /home/alex/Projects/ruby/test/foo_bar/config/main.rb:52:in `<top (required)>'
  config/puma.rb:6:in `require_relative'
  config/puma.rb:6:in `_load_from'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/dsl.rb:46:in `instance_eval'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/dsl.rb:46:in `_load_from'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:195:in `block in load'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:195:in `each'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:195:in `load'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/control_cli.rb:95:in `initialize'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/bin/pumactl:5:in `new'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/bin/pumactl:5:in `<top (required)>'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/pumactl:23:in `load'
  /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/pumactl:23:in `<top (required)>'
```

Although it's defined in `Gemfile` and should be loaded.

Wrapping `system` call into `Bundler.with_unbundled_env do` helps (as I see), but it's strange.

**Comment by AlexWayfer** [comment]
I can use `system 'command'`, without `bundle exec` inside, and it will work without `Bundler.with_unbundled_env`. Still strange, but OK.

**Comment by dazuma** [comment]
Yeah, this makes sense to me. Don't `bundle exec` if you've already set up bundler by running `include :bundler`. It causes two problems:
* First, it's redundant. All `bundle exec` does is set up bundler, but you've already done so by running `include :bundler`. So you really don't need to do it again.
* Second, and more subtly, when you run `include :bundler`, Toys needs to modify your bundle to make sure it includes Toys itself. But `bundle exec` doesn't know that, so it gets confused. That's why you get the "cannot load" exception.

The reason `Bundler.with_unbundled_env` works around the issue is that it "resets" bundler, wiping out the Toys-created bundle so that `bundle exec` has a clean slate to work with. So _if_ for some reason you _must_ use `bundle exec`, then you can wrap it with `Bundler.with_unbundled_env` and that should work. But you should only need to do this if you have a _separate_ bundle that you need to load for whatever command you're running. If you're okay with using the same `Gemfile` both to define tools and to run pumactl, then omitting `bundle exec` is probably better.
